import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider.jsx";
import { Toaster } from "sonner";

import Header from "../components/header";
import { ConvexClientProvider } from "./ConvexClientProvider";
import { ClerkProvider } from "@clerk/nextjs";
import { shadesOfPurple } from "@clerk/themes";
import { FloatingShapes } from "../components/floating-shapes";
const inter = Inter({subsets: ["latin"]});



export const metadata = {
  title: "AI PHOTO EDITOR",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   
   <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className}`}
      >
         <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ClerkProvider appearance={{baseTheme: shadesOfPurple}}>

             <ConvexClientProvider>
              
            <Header/>
            <main className="min-h-screen bg-slate-900 text-white overflow-x-hidden"> 

            <FloatingShapes />
          <Toaster richColors/>

            {children}
            </main>
             </ConvexClientProvider>
            </ClerkProvider>
          </ThemeProvider>
      </body>
    </html>
  );
}
